### ISSUE TITLE
Additional panel - load filters by config

### ISSUE THREAD

**Issue by stefanocudini** [openmove/odh-mentor-otp#95]
this issue is related to:
https://github.com/openmove/odh-mentor-otp/issues/82

_provider_,_accesstype_,... is name of property pass to component https://bit.ly/39TmUU1

the panel is built following the config each property is a subpanel contains list of possible values

![Screenshot at 2021-09-30 13-31-44](https://user-images.githubusercontent.com/47107/135447608-0890b626-ff92-4922-82de-015dac845cca.png)

proposal of config.yml structure for each overlays

```yml
    - type: charger
      name: charger
      api: https://charger.otp.opendatahub.testingmachine.eu/charger/stations.json
 filters:
        provider:
          enabled: true
          label: label_provider
          values:
            - value: H2 Center
              enabled: true
            - value: AER
              enabled: true
            - value: Neogy
              enabled: true
            - value: EDY
              enabled: true
            - value: Alperia Smart Mobility
              enabled: true
            - value: ASM
              enabled: true
            - value: NHP
              enabled: true
            - value: ASD
              enabled: true
            - value: DriWe
              enabled: true
            - value: Route220
              enabled: true
            - value: AP_GEN
              enabled: true
        accessType:
          enabled: true
          label: label_accesstype
          values:
            - value: PUBLIC
              enabled: true
            - value: undefined
              enabled: true
            - value: PRIVATE
              enabled: true
            - value: PRIVATE_WITHPUBLICACCESS
              enabled: true
        reservable:
          enabled: true
          label: label_reservable
          values:
            - value: 'true'
              enabled: true
            - value: undefined
              enabled: true
            - value: 'false'
              enabled: true
            - value: 'null'
              enabled: true
        state:
          enabled: true
          label: label_state
          values:
            - value: AVAILABLE
              enabled: true
            - value: MAINTENANCE
              enabled: true
            - value: ACTIVE
              enabled: true
            - value: TEMPORARYUNAVAILABLE
              enabled: true
            - value: UNKNOWN
              enabled: true
            - value: undefined
              enabled: true
            - value: FAULT
              enabled: true
            - value: UNAVAILABLE
              enabled: true
            - value: 'null'
              enabled: true
            - value: OCCUPIED
              enabled: true
```
